#!/usr/bin/env python3
"""Aggregate results/robustness_matrix.json into the numbers + LaTeX tables
used in the paper. Reproducible: paper carries no hand-typed numbers.

Usage: uv run python scripts/aggregate_matrix_tables.py
Writes LaTeX to results/tables/robustness_*.tex and prints summary aggregates.
"""
import json
import os
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MATRIX = os.path.join(ROOT, "results", "robustness_matrix.json")
OUTDIR = os.path.join(ROOT, "results", "tables")
os.makedirs(OUTDIR, exist_ok=True)

ATTACKS = ["paraphrase", "back_translation", "one_hot_swap", "textfooler", "bae"]
ATTACK_LABEL = {
    "paraphrase": "Bangla Paraphrase",
    "back_translation": "Back-Translation",
    "one_hot_swap": "One-Hot Swap",
    "textfooler": "TextFooler$^\\dagger$",
    "bae": "BAE$^\\dagger$",
}
REGIME_LABEL = {
    "clean": "Undefended",
    "adv_paraphrase": "AT-Paraphrase",
    "adv_back_translation": "AT-BackTrans",
    "adv_all": "AT-All",
}
# Regimes that represent a defense (i.e. everything except the undefended baseline)
DEFENDED = ["adv_paraphrase", "adv_back_translation", "adv_all"]
MODEL_LABEL = {
    "banglabert": "BanglaBERT",
    "banglishbert": "BanglishBERT",
    "xlm-r": "XLM-R",
    "muril": "MuRIL",
    "indicbertv2": "IndicBERTv2",
}


def load():
    m = json.load(open(MATRIX))
    rows = []
    for key, cell in m.items():
        regime, model, dataset, seed = key.split("|")
        for atk, rec in cell.items():
            rows.append(dict(regime=regime, model=model, dataset=dataset,
                             attack=atk, asr=rec["asr"], n=rec["n"]))
    return rows


def mean(xs):
    xs = list(xs)
    return sum(xs) / len(xs) if xs else float("nan")


def by(rows, *keys):
    d = defaultdict(list)
    for r in rows:
        d[tuple(r[k] for k in keys)].append(r["asr"])
    return {k: mean(v) for k, v in d.items()}


def fmt(x):
    return f"{100*x:.1f}"


def regime_attack_table(rows):
    """Rows = attacks, cols = defense regimes, cells = mean ASR (%) over models&datasets."""
    ra = by(rows, "attack", "regime")
    lines = [
        "% Auto-generated by scripts/aggregate_matrix_tables.py -- do not hand-edit.",
        "\\begin{table*}[htbp]", "\\centering",
        "\\caption{Residual attack success rate (\\%, lower is better) of each attack "
        "against models hardened with three adversarial-training (AT) regimes, averaged "
        "over five victim models and four datasets. $^\\dagger$ denotes external baseline "
        "attacks (TextFooler, BAE) evaluated under the identical protocol.}",
        "\\label{tab:robustnessMatrix}",
        "\\begin{tabular}{l" + "c" * len(REGIME_LABEL) + "c}",
        "\\toprule",
        "\\textbf{Attack} & " + " & ".join("\\textbf{%s}" % REGIME_LABEL[r]
                                            for r in REGIME_LABEL) + " & \\textbf{Mean} \\\\",
        "\\midrule",
    ]
    for atk in ATTACKS:
        cells = [ra.get((atk, r), float("nan")) for r in REGIME_LABEL]
        # reduction = undefended minus the best (lowest) defended regime
        undef = ra.get((atk, "clean"), float("nan"))
        best_def = min(ra.get((atk, r), float("nan")) for r in DEFENDED)
        lines.append(ATTACK_LABEL[atk] + " & " +
                     " & ".join(fmt(c) for c in cells) +
                     " & $-$" + fmt(undef - best_def) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}", ""]
    return "\n".join(lines)


def model_attack_table(rows):
    """Rows = models, cols = attacks, cells = mean ASR (%) over regimes&datasets."""
    ma = by(rows, "model", "attack")
    order = ["banglabert", "banglishbert", "xlm-r", "muril", "indicbertv2"]
    lines = [
        "% Auto-generated by scripts/aggregate_matrix_tables.py -- do not hand-edit.",
        "\\begin{table*}[htbp]", "\\centering",
        "\\caption{Per-model residual attack success rate (\\%) by attack, averaged over "
        "the three AT regimes and four datasets. Lower is more robust.}",
        "\\label{tab:perModel}",
        "\\begin{tabular}{l" + "c" * len(ATTACKS) + "}",
        "\\toprule",
        "\\textbf{Victim model} & " +
        " & ".join("\\textbf{%s}" % ATTACK_LABEL[a].replace("$^\\dagger$", "")
                   for a in ATTACKS) + " \\\\",
        "\\midrule",
    ]
    for mdl in order:
        cells = [ma.get((mdl, a), float("nan")) for a in ATTACKS]
        lines.append(MODEL_LABEL[mdl] + " & " + " & ".join(fmt(c) for c in cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}", ""]
    return "\n".join(lines)


def main():
    rows = load()
    # console summary
    print(f"cells: {len(rows)} attack-observations over "
          f"{len(set((r['model'],r['dataset'],r['regime']) for r in rows))} model/dataset/regime combos")
    print("\n== mean ASR by attack (all regimes, models, datasets) ==")
    for atk, v in sorted(by(rows, "attack").items(), key=lambda kv: -kv[1]):
        print(f"  {atk[0]:18s} {100*v:5.1f}%")
    print("\n== mean ASR by regime (all attacks) ==")
    for reg, v in sorted(by(rows, "regime").items(), key=lambda kv: kv[1]):
        print(f"  {reg[0]:22s} {100*v:5.1f}%")
    print("\n== mean ASR by model (all attacks) ==")
    for mdl, v in sorted(by(rows, "model").items(), key=lambda kv: kv[1]):
        print(f"  {mdl[0]:14s} {100*v:5.1f}%")

    t1 = regime_attack_table(rows)
    t2 = model_attack_table(rows)
    open(os.path.join(OUTDIR, "robustness_matrix.tex"), "w").write(t1)
    open(os.path.join(OUTDIR, "robustness_permodel.tex"), "w").write(t2)
    print(f"\nwrote {OUTDIR}/robustness_matrix.tex and robustness_permodel.tex")


if __name__ == "__main__":
    main()
